# Site settings
title: Michael Laskey
description: Generative AI and the Law
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Michael Laskey
user_description: Partner at a leading Canadian law firm, focused on competition and regulatory law. I explore how generative AI can reshape legal practice—from automating workflows like docketing and lease review to supporting more efficient, human-centered legal analysis. I’m especially interested in building practical AI tools that lawyers actually use.
user_title: Lawyer
email: mlaskey@stikeman.com
twitter_username: mikelaskey1
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
linkedin_username: michael-laskey-45957239
github_username:  laskey
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

